const settingList = {
  theme: '主题',
  keyboardHandler: '快捷键绑定',
  fontSize: '字体大小',
  wrap: '换行模式',
  cursorStyle: '光标样式',
  foldStyle: '折叠',
  useSoftTabs: '空格缩进',
  tabSize: '缩进大小',
  scrollPastEnd: '过度滚动',
  behavioursEnabled: '启用快捷键',
  selectionStyle: '点击行号选择一行',
  highlightActiveLine: '高亮当前行',
  showInvisibles: '显示不可见字符',
  displayIndentGuides: '显示缩进导航',
  hScrollBarAlwaysVisible: '永久显示滚动条h',
  vScrollBarAlwaysVisible: '永久显示滚动条v',
  animatedScroll: '滚动动画',
  showGutter: '显示行号栏',
  showLineNumbers: '显示行号',
  fixedWidthGutter: '固定行号栏宽度',
  highlightSelectedWord: '高亮选中字符',
  readOnly: '只读模式',
  copyWithEmptySelection: '不选择复制',
  enableLiveAutocompletion: '自动补全(实时)',
  enableSnippets: '自动补全(snippets)',
  enableBasicAutocompletion: '自动补全(基础)',
  skin_url: 'TinyMCE皮肤',
  body_class: 'TinyMCE样式class',
  content_css: 'TinyMCE样式表地址',
  previewCss: '预览样式表地址',
  previewClass: '预览样式class',
  delayToHtml: '延迟渲染',
  scrollBind: '滚动绑定',
  pasteFormat: '粘贴格式化',
  pasteImageUpload: '粘贴图片上传',
  enableTinyMCE: '开启TinyMCE编辑器'
};

export default settingList;
